name: fe workflow

on:
  push:
    branches: ["main"]
    paths: 
      - "NodeJS/github-actions/react-express/todo-app-react/**"
      - ".github/workflows/fe-workflow.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
        include:
          - environment: dev
            github_environment: Development
            artifact_name: react-build-dev
          - environment: staging
            github_environment: Staging
            artifact_name: react-build-staging
          - environment: prod
            github_environment: Production
            artifact_name: react-build-prod
    environment: ${{ matrix.github_environment }}
    defaults:
      run:
        working-directory: ./NodeJS/github-actions/react-express/todo-app-react
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Build for ${{ matrix.environment }}
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
      - name: Upload ${{ matrix.environment }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: NodeJS/github-actions/react-express/todo-app-react/dist


  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: react-build-dev
          path: build

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: github-action-sandbox-fe-dev
          package: build

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: react-build-staging
          path: build
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: github-action-sandbox-fe-staging
          package: build

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: react-build-prod
          path: build
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Production
        uses: azure/webapps-deploy@v2
        with:
          app-name: github-action-sandbox-fe2
          package: build