name: fe workflow

on:
  push:
    branches: ["main"]
    paths: 
      - "NodeJS/github-actions/react-express/todo-app-react/**"
      - ".github/workflows/fe-workflow.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./NodeJS/github-actions/react-express/todo-app-react
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: NodeJS/github-actions/react-express/todo-app-react/dist

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: react-build
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: github-action-sandbox-fe2
          package: ./react-build

  # deploy-staging:
  #   needs: deploy-dev
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: staging
  #     url: https://your-staging-url
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: react-build
  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     - name: Deploy to Staging
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: your-staging-app-name
  #         package: ./react-build

  # deploy-prod:
  #   needs: deploy-staging
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: production
  #     url: https://your-prod-url
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: react-build
  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     - name: Deploy to Production
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: your-prod-app-name
  #         package: ./react-build